"""create organizations"""
from alembic import op
import sqlalchemy as sa

revision = "002"
down_revision = "001" if 1 else None


def upgrade():
    pass  # autogenerated


def downgrade():
    pass
