"""create notifications"""
from alembic import op
import sqlalchemy as sa

revision = "009"
down_revision = "008" if 8 else None


def upgrade():
    pass  # autogenerated


def downgrade():
    pass
